temp-directory: "./.nyc_output"
check-coverage: true
per-file: true
lines: 90
statements: 90
functions: 90
branches: 90
all: true
reporter: [
  "lcov"
]
exclude: [
  "src/index.ts", # Ignoring this until there is a reason to test this file. Currently just exports the library functions.
  "**/node_modules/**",
  "test/**"
]
